# -*- coding: utf-8 -*-
"""Terms & Conditions copy, per language.

Supplied by the client as one Word document holding all three versions, and
extracted from it rather than retyped. Each language is authored separately —
they are NOT translations generated from the Romanian, so this page is the one
place the i18n build does not run its dictionary over: build_i18n.py renders
this body per locale and leaves the surrounding chrome to the usual pass. The
three versions do not even share a shape — section 4 lists five prohibited uses
in Romanian and six in English and Russian, because that is how it was written.

Block kinds: ('h2', text) opens a section, ('p', html) a paragraph,
('ul', [html, ...]) a list. Inline HTML is limited to <strong> and <br>,
carried from the document's own bold runs and hard line breaks; headings are
plain text because the stylesheet already sets their weight.

Two things were corrected against the source, both typography, neither
touching meaning: adjacent bold runs are merged (Word had split "Telefon Ro:"
across two, which would render as two <strong> elements), and the English
contact block's "Ro Phone: : 40 724395919" loses its doubled colon.
"""

TERMS = {
    'ro': {
        'title': 'Termeni și condiții',
        'updated': 'Ultima actualizare: septembrie 2026',
        'lede': [
            'Prezentele Termeni și Condiții stabilesc cadrul general de utilizare a site-ului dedicat francizei <strong>Istorii cu Cașcaval</strong>, inclusiv condițiile privind accesarea informațiilor despre franciză și transmiterea unei aplicații pentru a deveni francizat.',
            'Prin accesarea, navigarea sau utilizarea site-ului și, după caz, prin transmiterea formularului de aplicare pentru franciză, utilizatorul confirmă că a citit, a înțeles și acceptă prezentele Termeni și Condiții.',
        ],
        'intro': [
            ('p', 'Site-ul este administrat de:'),
            ('p', '<strong>Istorii cu Cașcaval SRL</strong><br><strong>Telefon:</strong> +373 78013333<br><strong>Telefon Ro:</strong> 40 724395919<br><strong>Email:</strong> adrian@icascaval.md<br><strong>Website principal:</strong> icascaval.md'),
            ('p', 'În cazul în care nu sunteți de acord cu prevederile de mai jos, vă rugăm să nu utilizați acest site și să nu transmiteți o aplicație pentru franciză.'),
        ],
        'body': [
            ('h2', '1. Noțiuni utilizate'),
            ('p', 'În sensul prezentelor Termeni și Condiții:'),
            ('p', '<strong>Compania / Francizorul</strong> – Istorii cu Cașcaval SRL, administratorul site-ului și titularul sau utilizatorul autorizat al conceptului de franciză Istorii cu Cașcaval.'),
            ('p', '<strong>Site</strong> – platforma online dedicată prezentării oportunității de franciză Istorii cu Cașcaval și colectării aplicațiilor din partea persoanelor interesate.'),
            ('p', '<strong>Utilizator</strong> – orice persoană fizică sau juridică care accesează, navighează sau interacționează cu site-ul.'),
            ('p', '<strong>Candidat / Solicitant</strong> – persoana fizică sau juridică ce transmite o aplicație sau își exprimă interesul pentru obținerea unei francize Istorii cu Cașcaval.'),
            ('p', '<strong>Aplicație pentru franciză</strong> – informațiile și datele transmise prin formularul disponibil pe site sau prin alte mijloace de contact indicate de companie, în scopul evaluării unei eventuale colaborări.'),
            ('p', '<strong>Francizat</strong> – persoana fizică sau juridică ce a fost acceptată de companie și cu care a fost încheiat separat un contract de franciză.'),
            ('h2', '2. Scopul site-ului'),
            ('p', 'Site-ul are scop informativ și de prezentare a conceptului de franciză <strong>Istorii cu Cașcaval</strong>, a modelului de business, condițiilor generale de colaborare și oportunităților disponibile.'),
            ('p', 'De asemenea, site-ul permite persoanelor interesate să transmită o aplicație pentru franciză și să solicite informații suplimentare.'),
            ('p', 'Informațiile prezentate pe site nu reprezintă, prin ele însele, o ofertă contractuală fermă, un contract de franciză sau o garanție că persoana interesată va fi acceptată în rețeaua Istorii cu Cașcaval.'),
            ('h2', '3. Acceptarea condițiilor'),
            ('p', 'Prin utilizarea site-ului, utilizatorul confirmă că a citit și acceptă prezentele Termeni și Condiții.'),
            ('p', 'Transmiterea unei aplicații pentru franciză presupune acceptarea condițiilor aplicabile procesului de analiză și selecție descris pe această pagină.'),
            ('h2', '4. Utilizarea site-ului'),
            ('p', 'Utilizatorii se obligă să utilizeze site-ul în mod legal și responsabil, fără a prejudicia compania, alți utilizatori sau funcționarea platformei.'),
            ('p', 'Este interzisă:'),
            ('ul', [
                'accesarea neautorizată a sistemelor, bazelor de date sau secțiunilor protejate ale site-ului;',
                'transmiterea de informații false, frauduloase sau aparținând altor persoane fără autorizare;',
                'copierea, reproducerea, distribuirea sau utilizarea conținutului site-ului fără acordul companiei;',
                'utilizarea identității vizuale, mărcilor, conceptelor sau materialelor Istorii cu Cașcaval în scop comercial fără autorizare;',
                'orice acțiune care poate afecta securitatea sau funcționarea normală a site-ului.',
            ]),
            ('h2', '5. Aplicarea pentru franciză'),
            ('p', 'Persoanele interesate pot transmite o aplicație pentru franciză prin completarea formularului disponibil pe site.'),
            ('p', 'În cadrul aplicației pot fi solicitate informații precum:'),
            ('ul', [
                'numele și prenumele;',
                'datele de contact;',
                'localitatea sau regiunea în care candidatul dorește să dezvolte franciza;',
                'experiența profesională sau antreprenorială;',
                'informații privind posibilitățile de investiție;',
                'disponibilitatea pentru implicarea în administrarea afacerii;',
                'alte informații relevante pentru evaluarea candidaturii.',
            ]),
            ('p', 'Transmiterea formularului reprezintă exclusiv o manifestare de interes din partea candidatului.'),
            ('p', '<strong>Transmiterea unei aplicații nu obligă compania să accepte candidatul, să ofere o franciză sau să încheie un contract.</strong>'),
            ('h2', '6. Evaluarea candidaturilor'),
            ('p', 'Compania își rezervă dreptul de a analiza fiecare aplicație conform propriilor criterii comerciale și operaționale.'),
            ('p', 'În procesul de evaluare, compania poate contacta candidatul pentru:'),
            ('ul', [
                'solicitarea unor informații suplimentare;',
                'clarificarea informațiilor transmise;',
                'organizarea unei discuții sau întâlniri;',
                'prezentarea mai detaliată a conceptului de franciză;',
                'evaluarea locației sau pieței propuse;',
                'continuarea etapelor de selecție.',
            ]),
            ('p', 'Compania își rezervă dreptul de a accepta sau respinge orice aplicație, inclusiv fără obligația de a furniza o justificare detaliată, în măsura permisă de legislația aplicabilă.'),
            ('p', 'Transmiterea aplicației nu conferă candidatului un drept asupra unei anumite locații, regiuni sau teritoriu.'),
            ('h2', '7. Corectitudinea informațiilor furnizate'),
            ('p', 'Candidatul este responsabil pentru furnizarea unor informații reale, complete și actualizate.'),
            ('p', 'Compania poate întrerupe procesul de evaluare dacă constată că informațiile furnizate sunt false, incomplete, înșelătoare sau nu pot fi verificate în mod rezonabil.'),
            ('p', 'Candidatul are obligația de a nu transmite date confidențiale aparținând unor terțe persoane fără drept sau autorizație.'),
            ('h2', '8. Încheierea unui contract de franciză'),
            ('p', 'Acceptarea unei aplicații, desfășurarea unor discuții, întâlniri, negocieri sau transmiterea unor materiale informative <strong>nu reprezintă încheierea unui contract de franciză</strong>.'),
            ('p', 'Un raport contractual de franciză va exista doar după negocierea condițiilor finale și semnarea unui contract separat între companie și francizat, conform legislației aplicabile.'),
            ('p', 'Condițiile finale privind investiția, taxele, teritoriul, drepturile și obligațiile părților, standardele de operare, durata colaborării și alte aspecte comerciale vor fi stabilite în contractul de franciză și în documentele aferente.'),
            ('p', 'În cazul unor diferențe între informațiile generale prezentate pe acest site și contractul de franciză semnat ulterior, prevederile contractului semnat vor prevala.'),
            ('h2', '9. Informații financiare și comerciale'),
            ('p', 'Orice informații de pe site privind:'),
            ('ul', [
                'investiția estimativă;',
                'costurile de lansare;',
                'perioada estimată de recuperare a investiției;',
                'cifra de afaceri;',
                'profitabilitatea;',
                'marjele;',
                'performanțele unor locații existente;',
                'potențialul pieței;',
            ]),
            ('p', 'au caracter informativ și orientativ, dacă nu este indicat în mod expres altfel.'),
            ('p', 'Rezultatele unei afaceri în sistem de franciză pot varia în funcție de numeroși factori, inclusiv locație, piață, concurență, management, costuri operaționale, echipă, implicarea francizatului și condițiile economice generale.'),
            ('p', '<strong>Istorii cu Cașcaval SRL nu garantează un anumit nivel al veniturilor, profitului sau recuperării investiției.</strong>'),
            ('p', 'Candidatul este încurajat să efectueze propria analiză comercială, financiară, fiscală și juridică înainte de asumarea unei investiții.'),
            ('h2', '10. Disponibilitatea teritoriilor și locațiilor'),
            ('p', 'Informațiile privind orașele, regiunile sau teritoriile disponibile pentru dezvoltarea francizei pot fi modificate în orice moment.'),
            ('p', 'Transmiterea unei aplicații pentru un anumit oraș sau teritoriu nu rezervă și nu garantează exclusivitatea acestuia.'),
            ('p', 'Orice drept de exclusivitate sau rezervare teritorială poate fi acordat numai în baza unui acord expres și, după caz, a contractului de franciză.'),
            ('h2', '11. Proprietate intelectuală'),
            ('p', 'Întreg conținutul site-ului, inclusiv, fără a se limita la:'),
            ('ul', [
                'denumirea Istorii cu Cașcaval;',
                'logo-uri și elemente de identitate vizuală;',
                'texte;',
                'fotografii;',
                'materiale video;',
                'elemente grafice;',
                'concepte;',
                'design;',
                'materiale de prezentare;',
                'structura și conținutul site-ului;',
            ]),
            ('p', 'aparține <strong>Istorii cu Cașcaval SRL</strong> sau este utilizat în mod legal de către companie.'),
            ('p', 'Accesarea site-ului sau transmiterea unei aplicații pentru franciză nu acordă utilizatorului niciun drept de utilizare comercială asupra mărcilor, identității vizuale, conceptului de business sau altor elemente de proprietate intelectuală ale companiei.'),
            ('p', 'Copierea, reproducerea, modificarea, distribuirea, publicarea sau utilizarea comercială a acestora fără acordul prealabil scris al companiei este interzisă.'),
            ('h2', '12. Confidențialitatea informațiilor privind franciza'),
            ('p', 'În cadrul procesului de evaluare, compania poate pune la dispoziția candidatului anumite informații suplimentare privind modelul de business, procesele interne, condițiile comerciale sau alte aspecte ale sistemului de franciză.'),
            ('p', 'Unele dintre aceste informații pot avea caracter confidențial.'),
            ('p', 'Compania poate solicita semnarea unui acord separat de confidențialitate înainte de furnizarea unor informații comerciale sensibile.'),
            ('p', 'Transmiterea unei aplicații nu oferă candidatului dreptul de a solicita sau de a distribui informații comerciale confidențiale ale companiei.'),
            ('h2', '13. Date cu caracter personal'),
            ('p', 'Datele furnizate prin formularul de aplicare, formularele de contact sau prin alte metode disponibile pe site vor fi prelucrate în conformitate cu legislația aplicabilă și cu <strong>Politica de Confidențialitate</strong> publicată pe site.'),
            ('p', 'Datele pot fi utilizate, în special, pentru:'),
            ('ul', [
                'recepționarea și analizarea aplicației;',
                'evaluarea compatibilității candidatului cu sistemul de franciză;',
                'contactarea candidatului;',
                'organizarea discuțiilor sau întâlnirilor;',
                'transmiterea informațiilor privind franciza;',
                'gestionarea etapelor procesului de selecție;',
                'îndeplinirea obligațiilor legale aplicabile.',
            ]),
            ('p', 'Informații suplimentare privind categoriile de date colectate, durata păstrării acestora, destinatarii datelor și drepturile persoanelor vizate sunt disponibile în Politica de Confidențialitate.'),
            ('h2', '14. Cookies și tehnologii similare'),
            ('p', 'Site-ul poate utiliza fișiere cookies și tehnologii similare necesare pentru funcționarea tehnică a platformei, precum și, în funcție de preferințele utilizatorului, pentru analiză, statistică, marketing sau optimizarea experienței de navigare.'),
            ('p', 'Utilizatorii pot gestiona preferințele privind cookies prin instrumentul de consimțământ disponibil pe site și/sau prin setările browserului.'),
            ('p', 'Informații detaliate sunt disponibile în <strong>Politica de Cookies</strong>.'),
            ('h2', '15. Servicii și platforme terțe'),
            ('p', 'Site-ul poate utiliza servicii furnizate de terți pentru funcționare, hosting, securitate, formulare, analiză, marketing, comunicare sau alte funcționalități.'),
            ('p', 'De asemenea, site-ul poate conține linkuri către alte website-uri sau platforme, inclusiv website-ul principal Istorii cu Cașcaval sau rețele sociale.'),
            ('p', 'Compania nu este responsabilă pentru conținutul, politicile sau practicile website-urilor terțe asupra cărora nu deține control.'),
            ('h2', '16. Limitarea răspunderii'),
            ('p', 'Compania depune eforturi rezonabile pentru ca informațiile publicate pe site să fie corecte și actualizate.'),
            ('p', 'Cu toate acestea, anumite informații privind conceptul de franciză, investițiile, disponibilitatea teritoriilor, etapele de dezvoltare sau alte elemente comerciale pot fi modificate.'),
            ('p', 'Compania nu garantează funcționarea permanentă și fără erori a site-ului și nu poate fi ținută răspunzătoare pentru:'),
            ('ul', [
                'întreruperi temporare ale funcționării site-ului;',
                'erori sau probleme tehnice independente de voința companiei;',
                'pierderi rezultate din interpretarea informațiilor generale de pe site ca reprezentând garanții comerciale sau financiare;',
                'decizii de investiție luate exclusiv în baza informațiilor generale publicate pe site;',
                'prejudicii generate de utilizarea necorespunzătoare a platformei.',
            ]),
            ('p', 'Nicio informație publicată pe site nu trebuie interpretată ca o garanție privind succesul unei viitoare afaceri în franciză.'),
            ('h2', '17. Forța majoră'),
            ('p', 'Compania nu va răspunde pentru neexecutarea unor obligații sau pentru indisponibilitatea temporară a serviciilor atunci când acestea sunt cauzate de evenimente de forță majoră sau de circumstanțe aflate în afara controlului său rezonabil, în conformitate cu legislația aplicabilă.'),
            ('h2', '18. Modificarea Termenilor și Condițiilor'),
            ('p', 'Compania își rezervă dreptul de a modifica sau actualiza prezentele Termeni și Condiții atunci când este necesar.'),
            ('p', 'Versiunea actualizată va fi publicată pe site și va produce efecte de la data publicării, cu excepția cazurilor în care legislația aplicabilă prevede altfel.'),
            ('p', 'Utilizatorii sunt încurajați să consulte periodic această pagină.'),
            ('h2', '19. Legea aplicabilă și soluționarea litigiilor'),
            ('p', 'Prezentele Termeni și Condiții sunt guvernate de legislația în vigoare a <strong>Republicii Moldova</strong>.'),
            ('p', 'Orice neînțelegere dintre companie și utilizator sau candidat va fi soluționată, în măsura posibilului, pe cale amiabilă.'),
            ('p', 'În cazul în care o soluționare amiabilă nu este posibilă, litigiul va fi deferit instanțelor competente conform legislației aplicabile.'),
            ('h2', '20. Date de contact'),
            ('p', 'Pentru întrebări privind site-ul, procesul de aplicare pentru franciză sau prezentele Termeni și Condiții, ne puteți contacta la:'),
            ('p', '<strong>Istorii cu Cașcaval SRL</strong><br><strong>Telefon:</strong> +373 78013333<br><strong>Telefon Ro:</strong> 40 724395919<br><strong>Email:</strong> adrian@icascaval.md'),
        ],
    },
    'en': {
        'title': 'Terms and Conditions',
        'updated': 'Last updated: September 2026',
        'lede': [
            'These Terms and Conditions establish the general framework for the use of the website dedicated to the Istorii cu Cașcaval franchise, including access to information about the franchise and the submission of an application to become a franchisee.',
            'By accessing, browsing or using the website and, where applicable, submitting a franchise application form, the user confirms that they have read, understood and accepted these Terms and Conditions.',
        ],
        'intro': [
            ('p', 'The website is operated by:'),
            ('p', 'Istorii cu Cașcaval SRL<br>Phone: +373 78013333<br>Ro Phone: 40 724395919<br>Email: adrian@icascaval.md'),
            ('p', 'If you do not agree with these Terms and Conditions, please do not use this website or submit a franchise application.'),
        ],
        'body': [
            ('h2', '1. Definitions'),
            ('p', 'For the purposes of these Terms and Conditions:'),
            ('p', 'Company / Franchisor – Istorii cu Cașcaval SRL, the website operator and the owner or authorised user of the Istorii cu Cașcaval franchise concept.'),
            ('p', 'Website – the online platform dedicated to presenting the Istorii cu Cașcaval franchise opportunity and collecting applications from interested persons.'),
            ('p', 'User – any individual or legal entity that accesses, browses or interacts with the website.'),
            ('p', 'Candidate / Applicant – any individual or legal entity that submits an application or expresses an interest in obtaining an Istorii cu Cașcaval franchise.'),
            ('p', 'Franchise Application – the information and data submitted through the form available on the website or through other contact methods indicated by the Company for the purpose of evaluating a potential collaboration.'),
            ('p', 'Franchisee – an individual or legal entity accepted by the Company with whom a separate franchise agreement has been concluded.'),
            ('h2', '2. Purpose of the Website'),
            ('p', 'The website is intended to provide information about the Istorii cu Cașcaval franchise concept, business model, general cooperation conditions and available opportunities.'),
            ('p', 'The website also allows interested persons to submit a franchise application and request additional information.'),
            ('p', 'The information available on the website does not, by itself, constitute a binding contractual offer, a franchise agreement or a guarantee that an interested person will be accepted into the Istorii cu Cașcaval franchise network.'),
            ('h2', '3. Acceptance of the Terms'),
            ('p', 'By using the website, the user confirms that they have read and accepted these Terms and Conditions.'),
            ('p', 'Submitting a franchise application also constitutes acceptance of the conditions applicable to the assessment and selection process described on this page.'),
            ('h2', '4. Use of the Website'),
            ('p', 'Users agree to use the website lawfully and responsibly and not to cause damage to the Company, other users or the operation of the platform.'),
            ('p', 'The following activities are prohibited:'),
            ('ul', [
                'unauthorised access to systems, databases or protected sections of the website;',
                'submitting false, fraudulent or misleading information;',
                'submitting information belonging to another person without authorisation;',
                "copying, reproducing, distributing or using website content without the Company's permission;",
                'using the Istorii cu Cașcaval name, visual identity, trademarks, concepts or materials for commercial purposes without authorisation;',
                'any action that may compromise the security or normal operation of the website.',
            ]),
            ('h2', '5. Franchise Application'),
            ('p', 'Interested persons may submit a franchise application by completing the form available on the website.'),
            ('p', 'The application may request information such as:'),
            ('ul', [
                'full name;',
                'contact details;',
                'city or region in which the candidate intends to develop the franchise;',
                'professional or entrepreneurial experience;',
                'information regarding investment capacity;',
                'availability to participate in the management of the business;',
                'other information relevant to evaluating the application.',
            ]),
            ('p', 'Submitting the form represents only an expression of interest by the candidate.'),
            ('p', 'Submitting an application does not oblige the Company to accept the candidate, grant a franchise or enter into an agreement.'),
            ('h2', '6. Assessment of Applications'),
            ('p', 'The Company reserves the right to assess each application according to its own commercial and operational criteria.'),
            ('p', 'During the assessment process, the Company may contact the candidate in order to:'),
            ('ul', [
                'request additional information;',
                'clarify information already provided;',
                'arrange a discussion or meeting;',
                'provide a more detailed presentation of the franchise concept;',
                'assess a proposed location or market;',
                'continue with further stages of the selection process.',
            ]),
            ('p', 'The Company reserves the right to accept or reject any application, including without providing detailed reasons, to the extent permitted by applicable law.'),
            ('p', 'Submitting an application does not give the candidate any right to a specific location, region or territory.'),
            ('h2', '7. Accuracy of Information'),
            ('p', 'The candidate is responsible for providing accurate, complete and up-to-date information.'),
            ('p', 'The Company may discontinue the assessment process if it determines that the information provided is false, incomplete, misleading or cannot reasonably be verified.'),
            ('p', 'Candidates must not provide confidential information belonging to third parties without having the appropriate right or authorisation to do so.'),
            ('h2', '8. Conclusion of a Franchise Agreement'),
            ('p', 'Acceptance of an application, discussions, meetings, negotiations or the provision of informational materials do not constitute the conclusion of a franchise agreement.'),
            ('p', 'A contractual franchise relationship will arise only after the final terms have been negotiated and a separate written agreement has been signed between the Company and the franchisee in accordance with applicable law.'),
            ('p', 'Final conditions regarding investment, fees, territory, rights and obligations of the parties, operational standards, duration of the relationship and other commercial matters will be established in the franchise agreement and related documents.'),
            ('p', 'If any information provided on this website differs from the provisions of a subsequently signed franchise agreement, the signed franchise agreement shall prevail.'),
            ('h2', '9. Financial and Commercial Information'),
            ('p', 'Any information displayed on the website regarding:'),
            ('ul', [
                'estimated investment;',
                'launch costs;',
                'estimated payback period;',
                'turnover;',
                'profitability;',
                'margins;',
                'performance of existing locations;',
                'market potential;',
            ]),
            ('p', 'is provided for general informational and indicative purposes unless expressly stated otherwise.'),
            ('p', 'The results of a franchise business may vary depending on numerous factors, including location, market conditions, competition, management, operating costs, team performance, franchisee involvement and general economic conditions.'),
            ('p', 'Istorii cu Cașcaval SRL does not guarantee any specific level of revenue, profit or return on investment.'),
            ('p', 'Candidates are encouraged to conduct their own commercial, financial, tax and legal analysis before committing to an investment.'),
            ('h2', '10. Availability of Territories and Locations'),
            ('p', 'Information regarding cities, regions or territories available for franchise development may change at any time.'),
            ('p', 'Submitting an application for a particular city or territory does not reserve or guarantee exclusivity over that territory.'),
            ('p', 'Any exclusivity or territorial reservation may only be granted through an express agreement and, where applicable, the franchise agreement.'),
            ('h2', '11. Intellectual Property'),
            ('p', 'All website content, including but not limited to:'),
            ('ul', [
                'the Istorii cu Cașcaval name;',
                'logos and visual identity elements;',
                'texts;',
                'photographs;',
                'videos;',
                'graphic elements;',
                'concepts;',
                'designs;',
                'presentation materials;',
                'website structure and content;',
            ]),
            ('p', 'belongs to Istorii cu Cașcaval SRL or is lawfully used by the Company.'),
            ('p', "Accessing the website or submitting a franchise application does not grant the user any commercial rights to use the Company's trademarks, visual identity, business concept or other intellectual property."),
            ('p', "Copying, reproducing, modifying, distributing, publishing or commercially using such materials without the Company's prior written consent is prohibited."),
            ('h2', '12. Confidential Franchise Information'),
            ('p', 'During the assessment process, the Company may provide candidates with additional information regarding the business model, internal processes, commercial conditions or other elements of the franchise system.'),
            ('p', 'Some of this information may be confidential.'),
            ('p', 'The Company may require the candidate to sign a separate confidentiality agreement before receiving commercially sensitive information.'),
            ('p', "Submitting an application does not give the candidate a right to demand or distribute the Company's confidential commercial information."),
            ('h2', '13. Personal Data'),
            ('p', 'Personal data provided through the application form, contact forms or other methods available on the website will be processed in accordance with applicable law and the Privacy Policy published on the website.'),
            ('p', 'Personal data may be used in particular for:'),
            ('ul', [
                'receiving and reviewing the application;',
                "evaluating the candidate's suitability for the franchise system;",
                'contacting the candidate;',
                'arranging discussions or meetings;',
                'providing information regarding the franchise;',
                'managing the stages of the selection process;',
                'complying with applicable legal obligations.',
            ]),
            ('p', 'Further information regarding the categories of data collected, retention periods, data recipients and data subject rights is available in the Privacy Policy.'),
            ('h2', '14. Cookies and Similar Technologies'),
            ('p', "The website may use cookies and similar technologies required for its technical operation and, depending on the user's preferences, for analytics, statistics, marketing or optimisation of the browsing experience."),
            ('p', 'Users may manage their cookie preferences through the consent tool available on the website and/or through their browser settings.'),
            ('p', 'Further information is available in the Cookie Policy.'),
            ('h2', '15. Third-Party Services and Platforms'),
            ('p', 'The website may use third-party services for hosting, security, forms, analytics, marketing, communications or other functionality.'),
            ('p', 'The website may also include links to external websites or platforms, including the main Istorii cu Cașcaval website and social media platforms.'),
            ('p', 'The Company is not responsible for the content, policies or practices of third-party websites or services that are outside its control.'),
            ('h2', '16. Limitation of Liability'),
            ('p', 'The Company makes reasonable efforts to ensure that the information published on the website is accurate and up to date.'),
            ('p', 'However, information concerning the franchise concept, investment requirements, territory availability, development stages or other commercial aspects may be modified.'),
            ('p', 'The Company does not guarantee that the website will operate continuously or without errors and shall not be liable for:'),
            ('ul', [
                'temporary website interruptions;',
                "technical errors or issues beyond the Company's reasonable control;",
                'losses resulting from treating general information on the website as a commercial or financial guarantee;',
                'investment decisions made exclusively on the basis of general information published on the website;',
                'damage caused by improper use of the platform.',
            ]),
            ('p', 'No information published on the website should be interpreted as a guarantee of the success of any future franchise business.'),
            ('h2', '17. Force Majeure'),
            ('p', 'The Company shall not be liable for failure to perform obligations or temporary unavailability of services caused by force majeure events or circumstances beyond its reasonable control, in accordance with applicable law.'),
            ('h2', '18. Changes to these Terms and Conditions'),
            ('p', 'The Company reserves the right to modify or update these Terms and Conditions whenever necessary.'),
            ('p', 'The updated version will be published on the website and will take effect from the date of publication unless otherwise required by applicable law.'),
            ('p', 'Users are encouraged to review this page periodically.'),
            ('h2', '19. Governing Law and Dispute Resolution'),
            ('p', 'These Terms and Conditions are governed by the laws of the Republic of Moldova.'),
            ('p', 'Any dispute between the Company and a user or candidate shall, where possible, be resolved amicably.'),
            ('p', 'If an amicable solution cannot be reached, the dispute shall be submitted to the competent courts in accordance with applicable law.'),
            ('h2', '20. Contact Information'),
            ('p', 'For questions regarding the website, franchise application process or these Terms and Conditions, you may contact us at:'),
            ('p', 'Istorii cu Cașcaval SRL<br>Phone: +373 78013333<br>Ro Phone: 40 724395919<br>Email: adrian@icascaval.md'),
        ],
    },
    'ru': {
        'title': 'Условия использования',
        'updated': 'Последнее обновление: сентябрь 2026',
        'lede': [
            'Настоящие Условия использования устанавливают общие правила использования сайта, посвященного франшизе Istorii cu Cașcaval, включая ознакомление с информацией о франшизе и подачу заявки на получение франшизы.',
            'Посещая, просматривая или используя сайт, а также, при необходимости, отправляя форму заявки на франшизу, пользователь подтверждает, что ознакомился, понял и принимает настоящие Условия использования.',
        ],
        'intro': [
            ('p', 'Сайт управляется:'),
            ('p', 'Istorii cu Cașcaval SRL<br>Телефон: +373 78013333<br>Телефон Ру: +40 724395919<br>Email: adrian@icascaval.md'),
            ('p', 'Если вы не согласны с положениями настоящих Условий, пожалуйста, не используйте данный сайт и не отправляйте заявку на франшизу.'),
        ],
        'body': [
            ('h2', '1. Основные понятия'),
            ('p', 'В рамках настоящих Условий:'),
            ('p', 'Компания / Франчайзер – Istorii cu Cașcaval SRL, администратор сайта и владелец либо уполномоченный пользователь концепции франшизы Istorii cu Cașcaval.'),
            ('p', 'Сайт – онлайн-платформа, предназначенная для презентации франшизы Istorii cu Cașcaval и сбора заявок от заинтересованных лиц.'),
            ('p', 'Пользователь – любое физическое или юридическое лицо, которое посещает, просматривает или иным образом взаимодействует с сайтом.'),
            ('p', 'Кандидат / Заявитель – физическое или юридическое лицо, подавшее заявку или выразившее заинтересованность в получении франшизы Istorii cu Cașcaval.'),
            ('p', 'Заявка на франшизу – информация и данные, направленные через форму на сайте либо другими указанными Компанией способами связи с целью рассмотрения возможности сотрудничества.'),
            ('p', 'Франчайзи – физическое или юридическое лицо, принятое Компанией в систему франшизы и заключившее с Компанией отдельный договор франшизы.'),
            ('h2', '2. Назначение сайта'),
            ('p', 'Сайт носит информационный характер и предназначен для презентации концепции франшизы Istorii cu Cașcaval, бизнес-модели, общих условий сотрудничества и доступных возможностей развития.'),
            ('p', 'Сайт также позволяет заинтересованным лицам подать заявку на франшизу и запросить дополнительную информацию.'),
            ('p', 'Информация, представленная на сайте, сама по себе не является обязательным договорным предложением, договором франшизы или гарантией того, что заинтересованное лицо будет принято в сеть Istorii cu Cașcaval.'),
            ('h2', '3. Принятие условий'),
            ('p', 'Используя сайт, пользователь подтверждает, что ознакомился и согласен с настоящими Условиями.'),
            ('p', 'Отправляя заявку на франшизу, кандидат также принимает условия, относящиеся к процессу рассмотрения и отбора заявок.'),
            ('h2', '4. Использование сайта'),
            ('p', 'Пользователи обязуются использовать сайт законно и ответственно, не причиняя вреда Компании, другим пользователям или работе платформы.'),
            ('p', 'Запрещается:'),
            ('ul', [
                'получать несанкционированный доступ к системам, базам данных или защищенным разделам сайта;',
                'передавать ложную, мошенническую или вводящую в заблуждение информацию;',
                'передавать данные других лиц без соответствующего разрешения;',
                'копировать, воспроизводить, распространять или использовать содержимое сайта без разрешения Компании;',
                'использовать название, фирменный стиль, товарные знаки, концепции или материалы Istorii cu Cașcaval в коммерческих целях без разрешения;',
                'совершать действия, которые могут нарушить безопасность или нормальную работу сайта.',
            ]),
            ('h2', '5. Подача заявки на франшизу'),
            ('p', 'Заинтересованные лица могут подать заявку на франшизу, заполнив форму на сайте.'),
            ('p', 'В заявке может быть запрошена следующая информация:'),
            ('ul', [
                'имя и фамилия;',
                'контактные данные;',
                'город или регион, в котором кандидат планирует развивать франшизу;',
                'профессиональный или предпринимательский опыт;',
                'информация о возможностях инвестирования;',
                'готовность участвовать в управлении бизнесом;',
                'другая информация, необходимая для рассмотрения кандидатуры.',
            ]),
            ('p', 'Отправка формы является исключительно выражением заинтересованности кандидата.'),
            ('p', 'Отправка заявки не обязывает Компанию принимать кандидата, предоставлять ему франшизу или заключать с ним договор.'),
            ('h2', '6. Рассмотрение заявок'),
            ('p', 'Компания оставляет за собой право рассматривать каждую заявку на основании собственных коммерческих и операционных критериев.'),
            ('p', 'В процессе рассмотрения Компания может связаться с кандидатом для:'),
            ('ul', [
                'запроса дополнительной информации;',
                'уточнения предоставленных данных;',
                'организации разговора или встречи;',
                'более подробной презентации концепции франшизы;',
                'анализа предлагаемой локации или рынка;',
                'продолжения дальнейших этапов отбора.',
            ]),
            ('p', 'Компания оставляет за собой право принять или отклонить любую заявку, в том числе без предоставления подробного обоснования, в пределах, разрешенных применимым законодательством.'),
            ('p', 'Подача заявки не предоставляет кандидату каких-либо прав на определенную локацию, регион или территорию.'),
            ('h2', '7. Достоверность предоставленной информации'),
            ('p', 'Кандидат несет ответственность за предоставление достоверной, полной и актуальной информации.'),
            ('p', 'Компания вправе прекратить процесс рассмотрения заявки, если установит, что предоставленная информация является ложной, неполной, вводящей в заблуждение или не может быть разумным образом подтверждена.'),
            ('p', 'Кандидат не должен передавать конфиденциальные данные третьих лиц без соответствующего права или разрешения.'),
            ('h2', '8. Заключение договора франшизы'),
            ('p', 'Принятие заявки, проведение переговоров, встреч, обсуждений или предоставление информационных материалов не означает заключения договора франшизы.'),
            ('p', 'Договорные отношения в рамках франшизы возникают исключительно после согласования окончательных условий и подписания отдельного договора между Компанией и франчайзи в соответствии с применимым законодательством.'),
            ('p', 'Окончательные условия, касающиеся инвестиций, платежей, территории, прав и обязанностей сторон, операционных стандартов, срока сотрудничества и других коммерческих вопросов, устанавливаются договором франшизы и сопутствующими документами.'),
            ('p', 'Если информация, представленная на сайте, отличается от условий впоследствии подписанного договора франшизы, преимущественную силу имеют положения подписанного договора.'),
            ('h2', '9. Финансовая и коммерческая информация'),
            ('p', 'Любая размещенная на сайте информация относительно:'),
            ('ul', [
                'предполагаемого объема инвестиций;',
                'расходов на запуск;',
                'предполагаемого срока окупаемости;',
                'оборота;',
                'прибыльности;',
                'маржинальности;',
                'результатов существующих локаций;',
                'потенциала рынка;',
            ]),
            ('p', 'носит информационный и ориентировочный характер, если прямо не указано иное.'),
            ('p', 'Результаты бизнеса по франшизе могут существенно различаться в зависимости от множества факторов, включая местоположение, состояние рынка, конкуренцию, управление, операционные расходы, команду, степень вовлеченности франчайзи и общую экономическую ситуацию.'),
            ('p', 'Istorii cu Cașcaval SRL не гарантирует определенного уровня выручки, прибыли или окупаемости инвестиций.'),
            ('p', 'Кандидату рекомендуется провести собственный коммерческий, финансовый, налоговый и юридический анализ до принятия инвестиционных обязательств.'),
            ('h2', '10. Доступность территорий и локаций'),
            ('p', 'Информация о городах, регионах или территориях, доступных для развития франшизы, может изменяться в любое время.'),
            ('p', 'Подача заявки на определенный город или территорию не означает ее бронирование и не гарантирует предоставление исключительных прав.'),
            ('p', 'Любая территориальная эксклюзивность или резервирование территории может быть предоставлена только на основании отдельного соглашения и, при необходимости, договора франшизы.'),
            ('h2', '11. Интеллектуальная собственность'),
            ('p', 'Все содержимое сайта, включая, помимо прочего:'),
            ('ul', [
                'название Istorii cu Cașcaval;',
                'логотипы и элементы фирменного стиля;',
                'тексты;',
                'фотографии;',
                'видеоматериалы;',
                'графические элементы;',
                'концепции;',
                'дизайн;',
                'презентационные материалы;',
                'структуру и содержание сайта;',
            ]),
            ('p', 'принадлежит Istorii cu Cașcaval SRL либо используется Компанией на законных основаниях.'),
            ('p', 'Посещение сайта или подача заявки на франшизу не предоставляет пользователю коммерческих прав на использование товарных знаков, фирменного стиля, бизнес-концепции или других объектов интеллектуальной собственности Компании.'),
            ('p', 'Копирование, воспроизведение, изменение, распространение, публикация или коммерческое использование таких материалов без предварительного письменного согласия Компании запрещено.'),
            ('h2', '12. Конфиденциальная информация о франшизе'),
            ('p', 'В процессе рассмотрения заявки Компания может предоставить кандидату дополнительную информацию о бизнес-модели, внутренних процессах, коммерческих условиях или других аспектах системы франшизы.'),
            ('p', 'Некоторая такая информация может иметь конфиденциальный характер.'),
            ('p', 'До предоставления коммерчески чувствительной информации Компания может потребовать подписания отдельного соглашения о конфиденциальности.'),
            ('p', 'Подача заявки не предоставляет кандидату права требовать или распространять конфиденциальную коммерческую информацию Компании.'),
            ('h2', '13. Персональные данные'),
            ('p', 'Персональные данные, предоставленные через форму заявки, контактные формы или другими доступными на сайте способами, обрабатываются в соответствии с применимым законодательством и Политикой конфиденциальности, опубликованной на сайте.'),
            ('p', 'Данные могут использоваться, в частности, для:'),
            ('ul', [
                'получения и рассмотрения заявки;',
                'оценки соответствия кандидата требованиям системы франшизы;',
                'связи с кандидатом;',
                'организации переговоров или встреч;',
                'предоставления информации о франшизе;',
                'управления этапами процесса отбора;',
                'выполнения применимых законодательных требований.',
            ]),
            ('p', 'Дополнительная информация о категориях собираемых данных, сроках их хранения, получателях данных и правах субъектов персональных данных содержится в Политике конфиденциальности.'),
            ('h2', '14. Cookies и аналогичные технологии'),
            ('p', 'Сайт может использовать cookies и аналогичные технологии, необходимые для его технической работы, а также, в зависимости от предпочтений пользователя, для аналитики, статистики, маркетинга и оптимизации пользовательского опыта.'),
            ('p', 'Пользователь может управлять настройками cookies посредством инструмента управления согласием, доступного на сайте, и/или через настройки браузера.'),
            ('p', 'Подробная информация содержится в Политике использования Cookies.'),
            ('h2', '15. Сторонние сервисы и платформы'),
            ('p', 'Для работы сайта могут использоваться сторонние сервисы, включая услуги хостинга, безопасности, обработки форм, аналитики, маркетинга, коммуникаций и других функций.'),
            ('p', 'Сайт также может содержать ссылки на другие веб-сайты или платформы, включая основной сайт Istorii cu Cașcaval и социальные сети.'),
            ('p', 'Компания не несет ответственности за содержание, политику или практики сторонних сайтов и сервисов, которые находятся вне ее контроля.'),
            ('h2', '16. Ограничение ответственности'),
            ('p', 'Компания предпринимает разумные усилия для обеспечения точности и актуальности размещенной на сайте информации.'),
            ('p', 'При этом информация о концепции франшизы, необходимых инвестициях, доступности территорий, этапах развития и других коммерческих аспектах может изменяться.'),
            ('p', 'Компания не гарантирует постоянную и бесперебойную работу сайта и не несет ответственности за:'),
            ('ul', [
                'временные перебои в работе сайта;',
                'технические ошибки или проблемы, находящиеся вне разумного контроля Компании;',
                'убытки, возникшие вследствие восприятия общей информации сайта как коммерческой или финансовой гарантии;',
                'инвестиционные решения, принятые исключительно на основании общей информации, опубликованной на сайте;',
                'ущерб, вызванный ненадлежащим использованием платформы.',
            ]),
            ('p', 'Никакая информация, опубликованная на сайте, не должна рассматриваться как гарантия успеха будущего бизнеса по франшизе.'),
            ('h2', '17. Форс-мажор'),
            ('p', 'Компания не несет ответственности за неисполнение обязательств или временную недоступность сервисов, вызванные обстоятельствами непреодолимой силы или иными событиями, находящимися вне ее разумного контроля, в соответствии с применимым законодательством.'),
            ('h2', '18. Изменение Условий'),
            ('p', 'Компания оставляет за собой право изменять или обновлять настоящие Условия по мере необходимости.'),
            ('p', 'Обновленная версия публикуется на сайте и вступает в силу с момента публикации, если иное не предусмотрено применимым законодательством.'),
            ('p', 'Пользователям рекомендуется периодически просматривать данную страницу.'),
            ('h2', '19. Применимое законодательство и разрешение споров'),
            ('p', 'Настоящие Условия регулируются законодательством Республики Молдова.'),
            ('p', 'Любые разногласия между Компанией и пользователем или кандидатом по возможности разрешаются путем переговоров.'),
            ('p', 'Если урегулировать спор мирным путем невозможно, он передается на рассмотрение компетентных судебных органов в соответствии с применимым законодательством.'),
            ('h2', '20. Контактные данные'),
            ('p', 'По вопросам, связанным с использованием сайта, процессом подачи заявки на франшизу или настоящими Условиями, вы можете связаться с нами:'),
            ('p', 'Istorii cu Cașcaval SRL<br>Телефон: +373 78013333<br>Телефон Ру: +40 724395919<br>Email: adrian@icascaval.md'),
        ],
    },
}
